name: Lab 03 Tests

on:
  push:
    paths:
      - 'labs/lab03/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Lab03 Python tests
        run: python labs/lab03/test.py

      - name: Verify Flowgorithm files exist
        run: |
          for i in {1..6}; do
            file="labs/lab03/lab-03-${i}.fprg"
            if [ ! -f "$file" ]; then
              echo "❌ Missing $file"
              exit 1
            fi
          done
